---
title: "Acadia Data Exploration"
author: "Acadia Hegedus"
date: "2/25/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
##Acadia Hegedus
##2/24/22

#Data Exploration
acadia.data <- data[sample(nrow(data), 5000),] #random sample without replacement

#Creating our target variable
acadia.data <- acadia.data %>%
  mutate(error_temp = obs_tmp_k-fcst_tmp_k)%>%
  mutate(error_precip = obs_pr_m_day -fcst_pr_m_day)

options(scipen = 1000)
hist(acadia.data$error_precip)
hist(acadia.data$error_temp)

print(mean(acadia.data$error_precip))
print(mean(acadia.data$error_temp)) 

#CFSv2 tends to overpredict both precipitation and temperature

#Exploring a single pixel
data%>%
  filter(x == -103.50, y == 29.25)%>%
  ggplot(mapping = aes(x = forecast_target, y = obs_tmp_k)) +
  geom_point()

#look at mean of 24 forecasts
mean.one.pixel.data <- data%>%
  filter(x == -103.50, y == 29.25)%>%
  group_by(forecast_target)%>%
  mutate(mean_temp = mean(obs_tmp_k))%>%
  mutate(mean_precip = mean(obs_pr_m_day))

#graph mean temp over time for one pixel
mean.one.pixel.data%>%
  ggplot(mapping = aes(x = forecast_target, y = mean_temp)) +
  geom_point()

#graph mean precip over time for one pixel
mean.one.pixel.data%>%
  ggplot(mapping = aes(x = forecast_target, y = mean_precip)) +
  geom_point()

data%>%
  filter(x == -103.50, y == 29.25, forecast_target == 200501)%>%
  group_by(forecast_timestamp)
#why am I only seeing 24 predictions at a single pixel/forecast_target?
#I thought we would be seeing 28?

#checking for NAs
sum(is.na(data))
#isnt it fabulous to have no missing data?

data%>%
  filter(x == -103.50, y == 29.25, forecast_target == 200501)

```

