---
title: "make_data_(1prediction/day)"
output: html_document
last-edit: 04/06/2022 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE)
```

#Repeat the same process in concatenating all the data 
```{r}
df <- c(list.files(path = "./data/old",
                   pattern = "hindcasts.*.rds",
                   full.names = TRUE))#,
#list.files(path = "./data/new",
#pattern = "forecasts.*.rds",
#full.names = TRUE))

#concat all data
#we have to do it in 2 parts because it's too big!!!
print("concatenating hindcast subsets...")
N <- length(df)
tmp <- NULL
tmpL <- list()
for(i in 1:N) {#(N/2)) {
  print(i)
  tmp <- readRDS(df[i])
  tmpL[[i]] <- tmp
  gc() #clear garbage memory
}

#concatenate batch 1
#print("saving batch 1...")
hindcast_all <- dplyr::bind_rows(tmpL)
rm(tmpL)
rm(tmp)
```

***Here we reduce the size of the data set by randomly select one prediction per day. In this case, we are still able to keep the observed temperature and precitipation for that month. ***
```{r}
hindcast_all$forecast_timestamp <- substring(hindcast_all$forecast_timestamp, 1,8)

hindcast_one_fourth <- hindcast_all %>% 
  #head(100000) %>% for testing in a small sample
  group_by(cell,forecast_timestamp) %>% 
  slice_sample(n =1,replace =FALSE) %>% 
  ungroup() 

```

Resume similar process in sampling 10% of the data 
```{r}
#choose 10% of pixels at random
#read in hindcast_month_1_lead_1.rds
sample_data <- readRDS(file = df[1])

all_pixels <- sample_data%>%
  dplyr::select(fcst_cell)%>%
  unique()

pixel_subset <- all_pixels[sample(nrow(all_pixels), nrow(all_pixels)*0.1), ]

hindcast_subset <- hindcast_all%>%
  filter(fcst_cell %in% pixel_subset)



########################################
#add on temperature lags for months 1-12
########################################

#convert date columns to YearMonth objects
hindcast_subset$forecast_timestamp <- substring(hindcast_subset$forecast_timestamp, 1, 6)
hindcast_subset$forecast_timestamp <- ym(hindcast_subset$forecast_timestamp)
hindcast_subset$forecast_target <- ym(hindcast_subset$forecast_target)

#add lag years to join by
hindcast_subset <- hindcast_subset%>%
  mutate(lag1 = add_with_rollback(hindcast_subset$forecast_timestamp, months(-1)),
         lag2 = add_with_rollback(hindcast_subset$forecast_timestamp, months(-2)),
         lag3 = add_with_rollback(hindcast_subset$forecast_timestamp, months(-3)),
         lag4 = add_with_rollback(hindcast_subset$forecast_timestamp, months(-4)),
         lag5 = add_with_rollback(hindcast_subset$forecast_timestamp, months(-5)),
         lag6 = add_with_rollback(hindcast_subset$forecast_timestamp, months(-6)),
         lag7 = add_with_rollback(hindcast_subset$forecast_timestamp, months(-7)),
         lag8 = add_with_rollback(hindcast_subset$forecast_timestamp, months(-8)),
         lag9 = add_with_rollback(hindcast_subset$forecast_timestamp, months(-9)),
         lag10 = add_with_rollback(hindcast_subset$forecast_timestamp, months(-10)),
         lag11 = add_with_rollback(hindcast_subset$forecast_timestamp, months(-11)),
         lag12 = add_with_rollback(hindcast_subset$forecast_timestamp, months(-12)))

#create observed data set (lag.data)
lag.data <- hindcast_subset%>%
  dplyr::select(forecast_target,obs_pr_m_day,obs_tmp_k, fcst_cell)%>%
  unique()

colnames(lag.data)[1] <- "date"

#left_join hindcast_subset with lag.data for each lag column, changing lagi to observed temp
hindcast_subset_temp_lags <- hindcast_subset
for (i in (1:12)){
  mylag <- paste0("lag",i)
  hindcast_subset_temp_lags <- left_join(hindcast_subset_temp_lags, lag.data, by = 
                                           c("fcst_cell", setNames("date", mylag)))
  hindcast_subset_temp_lags[mylag] <- hindcast_subset_temp_lags[,26] #grab observed temp column
  hindcast_subset_temp_lags <- hindcast_subset_temp_lags[,1:24]
}



########################################
#append elevation data for all cells
########################################

#get complete elevation data
elev <- rast('./data/gmted2010_ERA5_quarter_degree.tif')
elev_df <- as.data.frame(elev, xy=TRUE)
hindcast_subset_temp_lags <- left_join(hindcast_subset_temp_lags, elev_df, 
                                       by = c("x", "y"))
colnames(hindcast_subset_temp_lags)[25] <- "elevation" 



########################################
#save subset
########################################

#get and format current datetime for filename
currentTime <- Sys.time()
currentTime <- gsub(" ", "_", currentTime)
currentTime <- gsub(":", "-", currentTime)

#format filename as:
# hindcast_subset_, number of selected rows, _, current date and time
filename <- paste0("./data/", "hindcast_subset(1/4)_", nrow(pixel_subset), "_", currentTime)

print(paste0("saving as ", filename, "..."))
saveRDS(hindcast_subset_temp_lags, file = filename)
```


